version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: youtube_video_fetcher
      POSTGRES_USER: youtube_admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://youtube_admin:admin@db:5432/youtube_video_fetcher
    volumes:
      - .:/app

volumes:
  postgres_data:
