version: '3.9'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: youtube_video_fetcher
      POSTGRES_USER: youtube_admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://youtube_admin:admin@db:5432/youtube_video_fetcher
    depends_on:
      - db
    volumes:
      - .:/app
    expose:
      - "8000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
